name: simple pipeline

on:
  push:
    branches: [main]

jobs:
    lintTest:
      name: Lint
      runs-on: ubuntu-latest
      steps:
        - name: Clone Repository
          uses: actions/checkout@v2
        - name: Install Dependencies
          run: |
            echo "Running and Installing Dependencies ..."
            npm install
        - name: Run Linting
          run: |
            echo "Running Linting tests .."
            npm run lint
          env:
            CI: true
    securityCheck:
        name: Security Check
        runs-on: ubuntu-latest
        steps:
        - name: Checks the Security
          run: |
            echo "Running Securuty Checks .."
            sleep 5s;
            echo "Running Securuty Checks .."
            sleep 5s;
            echo "Running Securuty Checks .."
            sleep 5s;
          env:
            CI: true   



